package com.rafarg.ecogardengame.model

import androidx.compose.animation.core.*
import androidx.compose.foundation.clickable
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.layout.*
import androidx.compose.material3.Text
import androidx.compose.runtime.*
import androidx.compose.runtime.snapshots.SnapshotStateList
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.alpha
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.unit.IntOffset
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.rafarg.ecogardengame.ui.SpriteAnimation
import ecogardengame.composeapp.generated.resources.*
import ecogardengame.composeapp.generated.resources.Res
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import org.jetbrains.compose.resources.DrawableResource
import org.jetbrains.compose.resources.StringResource
import org.jetbrains.compose.resources.painterResource
import kotlin.math.PI
import kotlin.math.cos
import kotlin.math.sin
import kotlin.random.Random

/**
 * Represents a single type of reward gained from interacting with a vegetable.
 * @property emoji The emoji representation of the reward (e.g., "🍅", "🪙").
 * @property moneyValue The amount of money this reward grants.
 * @property countValue The amount of items (vegetables) this reward grants.
 * @property resource Optional drawable resource for animating the reward particle.
 * @property isLucky Indicates if this reward was generated by a "Lucky Harvest" event.
 */
data class Reward(
    val emoji: String, 
    val moneyValue: Int = 0, 
    val countValue: Int = 1,
    val resource: DrawableResource? = null,
    val isLucky: Boolean = false
)

/**
 * Represents the cost (money and items) required to unlock something in the game.
 * @property money The money cost.
 * @property vegetableCosts A map of vegetable IDs to the required amount.
 */
data class ItemCost(
    val money: Int = 0,
    val vegetableCosts: Map<String, Int> = emptyMap()
)

/**
 * Represents a particle that "flies" away from the clicked vegetable to show rewards.
 */
class FlyingParticle(
    val id: Long,
    val emoji: String,
    val resource: DrawableResource? = null,
    val text: String = "",
    val animatableX: Animatable<Float, *> = Animatable(0f),
    val animatableY: Animatable<Float, *> = Animatable(0f),
    val animatableAlpha: Animatable<Float, *> = Animatable(0f),
    val isLucky: Boolean = false
) {
    /** Flag to trigger early removal of the particle (e.g., when too many are on screen). */
    var isManuallyRemoved by mutableStateOf(false)
}

/**
 * Represents a gameplay modifier specific to a vegetable (e.g., "Haptic Timing" for Tomato).
 */
class GameplayModifier(
    val id: String,
    val nameRes: StringResource,
    val descriptionRes: StringResource,
    val unlockCost: ItemCost,
    val targetItemId: String,
    isUnlockedInitial: Boolean = false,
    isEnabledInitial: Boolean = false
) {
    var isUnlocked by mutableStateOf(isUnlockedInitial)
    var isEnabled by mutableStateOf(isEnabledInitial)
}

/**
 * Represents a global upgrade that affects all vegetables (e.g., "Lucky Harvest").
 */
class GlobalUpgrade(
    val id: String,
    val nameRes: StringResource,
    val descriptionRes: StringResource,
    val baseCost: ItemCost,
    val maxLevel: Int = 1,
    unlockedLevelInitial: Int = 0
) {
    var unlockedLevel by mutableStateOf(unlockedLevelInitial)
    
    val isUnlocked: Boolean get() = unlockedLevel > 0
    val isMaxLevel: Boolean get() = unlockedLevel >= maxLevel

    /**
     * Calculates the cost for the next level of the upgrade.
     */
    fun getNextLevelCost(): ItemCost {
        val multiplier = unlockedLevel + 1
        return ItemCost(
            money = baseCost.money * multiplier,
            vegetableCosts = baseCost.vegetableCosts.mapValues { it.value * multiplier }
        )
    }
}

/**
 * Interface defining the properties and behavior of a vegetable in the garden.
 */
interface GameItem {
    val id: String
    val nameRes: StringResource
    val resource: DrawableResource
    val price: Int
    val unlockCost: ItemCost
    var unlocked: Boolean
    val particleEmoji: String
    val tutorialRes: StringResource
    
    val baseRewards: List<Reward>
    val modifiers: List<GameplayModifier>

    /**
     * Composable function to render the vegetable and handle interactions.
     */
    @Composable
    fun Content(
        modifier: Modifier,
        onVegetableClick: (List<Reward>) -> List<Reward>,
        activeModifiers: List<GameplayModifier>,
        vibrationEnabled: Boolean,
        vibrationIntensity: Float
    )

    /**
     * Composable function to render flying particles for rewards.
     */
    @Composable
    fun ParticleEffect(particles: SnapshotStateList<FlyingParticle>)
}

/**
 * Abstract base class for vegetables that provides common functionality like particle creation.
 */
abstract class BaseVegetable : GameItem {
    
    override val baseRewards: List<Reward> get() = listOf(
        Reward(emoji = particleEmoji, countValue = 1, resource = resource),
        Reward(emoji = "🪙", moneyValue = 1, countValue = 0)
    )
    
    override val modifiers: List<GameplayModifier> = emptyList()

    /**
     * Helper to generate particles with consistent visual style and dispersion.
     */
    fun createRewardParticles(
        rewards: List<Reward>,
        offsetX: Float = 0f,
        offsetY: Float = 0f
    ): List<FlyingParticle> {
        val angle = Random.nextDouble(0.0, 360.0)
        val radius = Random.nextFloat() * 80f + 40f
        val radians = angle * (PI / 180.0)
        val baseStartX = (cos(radians) * radius).toFloat() + offsetX
        val baseStartY = (sin(radians) * radius).toFloat() + offsetY

        return rewards.mapIndexed { index, reward ->
            val isMoney = reward.moneyValue > 0
            val amount = if (isMoney) reward.moneyValue else reward.countValue
            val lineOffset = index * 70f

            FlyingParticle(
                id = Random.nextLong(), 
                emoji = reward.emoji,
                resource = if (isMoney) Res.drawable.coin_strip else reward.resource,
                text = "+$amount",
                animatableX = Animatable(baseStartX),
                animatableY = Animatable(baseStartY + lineOffset),
                animatableAlpha = Animatable(0f),
                isLucky = reward.isLucky
            )
        }
    }

    @Composable
    override fun Content(
        modifier: Modifier,
        onVegetableClick: (List<Reward>) -> List<Reward>,
        activeModifiers: List<GameplayModifier>,
        vibrationEnabled: Boolean,
        vibrationIntensity: Float
    ) {
        val scope = rememberCoroutineScope()
        val scale = remember { Animatable(1f) }
        val flyingParticles = remember { mutableStateListOf<FlyingParticle>() }

        Box(contentAlignment = Alignment.Center) {
            SpriteAnimation(
                painter = painterResource(resource),
                frameCount = 3,
                modifier = modifier
                    .size(220.dp)
                    .graphicsLayer {
                        scaleX = scale.value
                        scaleY = scale.value
                    }
                    .clickable(
                        interactionSource = remember { MutableInteractionSource() },
                        indication = null
                    ) {
                        val finalRewards = onVegetableClick(baseRewards)
                        
                        scope.launch {
                            scale.animateTo(0.8f, spring(Spring.DampingRatioLowBouncy, Spring.StiffnessMedium))
                            scale.animateTo(1f, spring(Spring.DampingRatioLowBouncy, Spring.StiffnessMedium))
                        }
                        
                        val newOnes = createRewardParticles(finalRewards)
                        
                        // Limit to 20 active particles to maintain performance
                        val activeCount = flyingParticles.count { !it.isManuallyRemoved }
                        val overflow = (activeCount + newOnes.size) - 20
                        if (overflow > 0) {
                            flyingParticles.filter { !it.isManuallyRemoved }
                                .take(overflow)
                                .forEach { it.isManuallyRemoved = true }
                        }
                        
                        flyingParticles.addAll(newOnes)
                    }
            )

            ParticleEffect(flyingParticles)
        }
    }
    
    @Composable
    override fun ParticleEffect(particles: SnapshotStateList<FlyingParticle>) {
        particles.forEach { particle ->
            key(particle.id) {
                LaunchedEffect(particle.isManuallyRemoved) {
                    if (particle.isManuallyRemoved) {
                        particle.animatableAlpha.animateTo(0f, tween(250))
                        particles.remove(particle)
                        return@LaunchedEffect
                    }

                    val moveDistance = 100f
                    val animationDuration = 1200

                    launch {
                        particle.animatableAlpha.animateTo(1f, tween(300))
                        delay(500)
                        particle.animatableAlpha.animateTo(0f, tween(400))
                    }
                    
                    launch {
                        particle.animatableY.animateTo(
                            targetValue = particle.animatableY.value - moveDistance,
                            animationSpec = tween(durationMillis = animationDuration, easing = LinearEasing)
                        )
                        particles.remove(particle)
                    }
                }

                Box(
                    modifier = Modifier
                        .offset {
                            IntOffset(
                                x = particle.animatableX.value.toInt(),
                                y = particle.animatableY.value.toInt()
                            )
                        }
                        .alpha(particle.animatableAlpha.value),
                    contentAlignment = Alignment.Center
                ) {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        modifier = Modifier.padding(4.dp)
                    ) {
                        Text(
                            text = particle.text,
                            fontSize = if (particle.isLucky) 32.sp else 24.sp,
                            color = if (particle.isLucky) Color.Yellow else Color.White,
                            fontWeight = if (particle.isLucky) androidx.compose.ui.text.font.FontWeight.Bold else null,
                            style = androidx.compose.material3.LocalTextStyle.current.copy(
                                shadow = androidx.compose.ui.graphics.Shadow(
                                    color = androidx.compose.ui.graphics.Color.Black,
                                    offset = androidx.compose.ui.geometry.Offset(2f, 2f),
                                    blurRadius = 4f
                                )
                            )
                        )
                        Spacer(modifier = Modifier.width(4.dp))
                        if (particle.resource != null) {
                            SpriteAnimation(
                                painter = painterResource(particle.resource),
                                frameCount = 3,
                                modifier = Modifier.size(if (particle.isLucky) 40.dp else 30.dp)
                              )
                        } else {
                            Text(
                                text = particle.emoji,
                                fontSize = if (particle.isLucky) 32.sp else 24.sp
                            )
                        }
                    }
                }
            }
        }
    }
}
